- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install things i want
  package:
    name:
      - vim
      - python3-picamera2
      - nginx
      - apache2-utils
      - python3-pyqt5
      - python3-opengl
      - python3-picamera2
      - python3-passlib
    state: latest

- name: Install community.general collection
  command: ansible-galaxy collection install community.general
  register: install_general
  changed_when: '"Nothing to do." not in install_general.stdout'

- name: Disable SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication Yes"
    line: "PasswordAuthentication no"
  register: sshd_config

-

- name: Restart SSHD daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
